name: bovine_embryo_survival_prediction
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - scipy
  - numpy
  - pandas
  - jupyter
  - matplotlib
  - seaborn
  - scikit-learn
  - scikit-image
  - opencv
  - pyyaml
  - torchvision
  - pytorch
  - cudatoolkit=10.2
  - tensorflow
  - cloudpickle
  - xgboost

  # dev
  - flake8
  - black


  - pip
  - pip:
    - osfclient
    - ramp-workflow
